export const ADD_NEW_USER  = "ADD_NEW_USER";
export const SHOW_USER_BY_ID  = "SHOW_USER_BY_ID";
export const SHOW_ALL_USERS  = "SHOW_ALL_USERS";
export const SHOW_ALL_USERS_SUCCESS  = "SHOW_ALL_USERS_SUCCESS";
export const ADD_NEW_USER_SUCCESS  = "ADD_NEW_USER_SUCCESS";
export const SHOW_USER_BY_ID_SUCCESS  = "SHOW_USER_BY_ID_SUCCESS";
