export const ADD_NEW_USER  = "ADD_NEW_USER";
export const SHOW_USER_BY_NAME  = "SHOW_USER_BY_NAME";
export const SHOW_ALL_USERS  = "SHOW_ALL_USERS";
export const SHOW_ALL_USERS_SUCCESS  = "SHOW_ALL_USERS_SUCCESS";
export const ADD_NEW_USER_SUCCESS  = "ADD_NEW_USER_SUCCESS";
export const SHOW_USER_BY_NAME_SUCCESS  = "SHOW_USER_BY_NAME_SUCCESS";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
